# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26273ce001f9a13851d240499c13e7d4ad2e585075905499a3b85648b9bed68f1af5eb5409891e7d66fb43a6a095f9e4bf2850623038c9344d37365ad641fdcc

test:
  secret_key_base: 92dcc13bccc9ae6006d5f6fb903fb7ada8b771060aa645053e56de6c75f72f4219190ef4148fc518f118977f57a6d60ab76dc8819a4795bb0e41578b359d1c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
